version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres-db
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  cars:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: API
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/static

volumes:
  static_volume:
  pg_data: