version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - app_network

  cars:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: API
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/static
    networks:
      - app_network

volumes:
  static_volume:
  pg_data:

networks:
  app_network:
    external: true
    name: op